CREATE TABLE IF NOT EXISTS sys_dict (
    id              BIGSERIAL PRIMARY KEY,
    dict_type       VARCHAR(64)  NOT NULL,
    dict_code       VARCHAR(64)  NOT NULL,
    dict_name       VARCHAR(128) NOT NULL,
    order_num       INT          DEFAULT 0,
    status          VARCHAR(32)  DEFAULT 'ACTIVE',
    created_by      BIGINT,
    created_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_by      BIGINT,
    updated_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT     DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_sys_dict_type ON sys_dict(dict_type) WHERE deleted = 0;

INSERT INTO sys_dict (dict_type, dict_code, dict_name, order_num, status, created_by, created_at, updated_by, updated_at)
VALUES
    ('PROJECT_TYPE', 'MODEL',         '型号项目', 1, 'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('PROJECT_TYPE', 'PRE_RESEARCH',  '预研项目', 2, 'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('PROJECT_TYPE', 'TECH_IMPROVE',  '技改项目', 3, 'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('PROJECT_TYPE', 'PROD_SUPPORT',  '批产保障', 4, 'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('PROJECT_TYPE', 'OTHER',         '其他',     5, 'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;

-- GJB 5882-2006 技术文件内容分类 (15大类)
INSERT INTO sys_dict (dict_type, dict_code, dict_name, order_num, status, created_by, created_at, updated_by, updated_at)
VALUES
    ('DOC_CATEGORY', 'PROCESS',         '一般过程文件',   1,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_CATEGORY', 'SOFTWARE',        '软件文档',       2,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_CATEGORY', 'MANUFACTURE',     '工艺文件',       3,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_CATEGORY', 'STANDARDIZE',     '标准化文件',     4,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_CATEGORY', 'QUALITY',         '质量文件',       5,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_CATEGORY', 'RISK',            '风险管理文件',   6,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_CATEGORY', 'RELIABILITY',     '可靠性文件',     7,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_CATEGORY', 'MAINTAINABILITY', '维修性文件',     8,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_CATEGORY', 'TESTABILITY',     '测试性文件',     9,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_CATEGORY', 'SUPPORTABILITY',  '保障性文件',     10, 'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_CATEGORY', 'SAFETY',          '安全性文件',     11, 'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_CATEGORY', 'ENVIRONMENT',     '环境适应性文件', 12, 'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_CATEGORY', 'EMC',             '电磁兼容性文件', 13, 'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_CATEGORY', 'ERGONOMICS',      '人机工程文件',   14, 'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_CATEGORY', 'ACHIEVEMENT',     '项目成果文件',   15, 'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;

-- 文档子类型 (abstract sub-types, linked to DOC_CATEGORY via parent_code)
INSERT INTO sys_dict (dict_type, dict_code, dict_name, parent_code, order_num, status, created_by, created_at, updated_by, updated_at)
VALUES
    ('DOC_TYPE', 'DEVELOPMENT_PLAN',      '研制计划',           'PROCESS',         1,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'DESIGN_REVIEW',         '设计评审报告',       'PROCESS',         2,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'STAGE_REVIEW',          '转阶段评审报告',     'PROCESS',         3,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'FINALIZATION_REPORT',   '定型报告',           'PROCESS',         4,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'DEVELOPMENT_TASKBOOK',  '研制任务书',         'PROCESS',         5,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'SOFTWARE_REQ_SPEC',     '软件需求规格说明',   'SOFTWARE',        1,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'SOFTWARE_DESIGN_DOC',   '软件设计文档',       'SOFTWARE',        2,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'SOFTWARE_TEST_PLAN',    '软件测试计划',       'SOFTWARE',        3,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'SOFTWARE_TEST_REPORT',  '软件测试报告',       'SOFTWARE',        4,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'SOFTWARE_USER_MANUAL',  '软件用户手册',       'SOFTWARE',        5,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'PROCESS_MASTER_PLAN',   '工艺总方案',         'MANUFACTURE',     1,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'PROCESS_PROCEDURE',     '工艺规程',           'MANUFACTURE',     2,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'PROCESS_REVIEW_REPORT', '工艺评审报告',       'MANUFACTURE',     3,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'PROCESS_FINALIZATION',  '工艺定型文件',       'MANUFACTURE',     4,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'STD_MASTER_PLAN',       '标准化大纲',         'STANDARDIZE',     1,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'STD_WORK_REPORT',       '标准化工作报告',     'STANDARDIZE',     2,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'PRODUCT_SPEC',          '产品规范',           'STANDARDIZE',     3,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'STD_SELECTION_LIST',    '标准选用目录',       'STANDARDIZE',     4,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'STD_AUDIT_REPORT',      '标准化审查报告',     'STANDARDIZE',     5,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'QUALITY_PLAN',          '质量计划',           'QUALITY',         1,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'QUALITY_AUDIT_REPORT',  '质量审核报告',       'QUALITY',         2,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'QUALITY_ASSURE_OUTLINE','质量保证大纲',       'QUALITY',         3,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'QUALITY_IMPROVE_REPORT','质量改进报告',       'QUALITY',         4,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'RISK_MANAGE_PLAN',      '风险管理计划',       'RISK',            1,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'RISK_ASSESS_REPORT',    '风险评估报告',       'RISK',            2,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'RISK_CONTROL_PLAN',     '风险控制计划',       'RISK',            3,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'REL_ASSURE_OUTLINE',    '可靠性保证大纲',     'RELIABILITY',     1,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'REL_ALLOC_REPORT',      '可靠性分配报告',     'RELIABILITY',     2,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'REL_PREDICT_REPORT',    '可靠性预计报告',     'RELIABILITY',     3,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'REL_TEST_OUTLINE',      '可靠性试验大纲',     'RELIABILITY',     4,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'REL_TEST_REPORT',       '可靠性试验报告',     'RELIABILITY',     5,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'MAINT_ASSURE_OUTLINE',  '维修性保证大纲',     'MAINTAINABILITY', 1,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'MAINT_ALLOC_REPORT',    '维修性分配报告',     'MAINTAINABILITY', 2,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'MAINT_ANALYSIS_REPORT', '维修性分析报告',     'MAINTAINABILITY', 3,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'TEST_ASSURE_OUTLINE',   '测试性保证大纲',     'TESTABILITY',     1,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'TEST_DESIGN_REPORT',    '测试性设计报告',     'TESTABILITY',     2,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'TEST_VERIFY_REPORT',    '测试性验证报告',     'TESTABILITY',     3,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'SUPPORT_ASSURE_OUTLINE','保障性保证大纲',     'SUPPORTABILITY',  1,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'SUPPORT_PLAN',          '综合保障方案',       'SUPPORTABILITY',  2,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'SUPPORT_ASSESS_REPORT', '保障性评估报告',     'SUPPORTABILITY',  3,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'SAFETY_ANALYSIS_REPORT','安全性分析报告',     'SAFETY',          1,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'SAFETY_ASSURE_OUTLINE', '安全性保证大纲',     'SAFETY',          2,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'SAFETY_RISK_EVAL',      '安全风险评估',       'SAFETY',          3,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'ENV_ASSURE_OUTLINE',    '环境适应性保证大纲', 'ENVIRONMENT',     1,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'ENV_TEST_OUTLINE',      '环境试验大纲',       'ENVIRONMENT',     2,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'ENV_TEST_REPORT',       '环境试验报告',       'ENVIRONMENT',     3,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'EMC_ASSURE_OUTLINE',    '电磁兼容性保证大纲', 'EMC',             1,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'EMC_TEST_OUTLINE',      '电磁兼容性试验大纲', 'EMC',             2,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'EMC_TEST_REPORT',       '电磁兼容性试验报告', 'EMC',             3,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'HFE_ASSURE_OUTLINE',    '人机工程保证大纲',   'ERGONOMICS',      1,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'HFE_ANALYSIS_REPORT',   '人机工程分析报告',   'ERGONOMICS',      2,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'FEASIBILITY_REPORT',    '方案论证报告',       'ACHIEVEMENT',     1,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'PROJECT_SUMMARY',       '项目总结报告',       'ACHIEVEMENT',     2,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'TECH_SUMMARY',          '技术总结报告',       'ACHIEVEMENT',     3,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP),
    ('DOC_TYPE', 'DESIGN_SPEC',           '设计说明书',         'ACHIEVEMENT',     4,  'ACTIVE', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;
